peter = int(input("Enter Peter's birthday (dd/mm/yyyy): "))
parker = int(input("Enter Parker's birthday (dd/mm/yyyy): "))
tom = int(input("Enter Tom's birthday (dd/mm/yyyy): "))
mitchell = int(input("Enter Mitchell's birthday (dd/mm/yyyy): "))
tim = int(input("Enter Tim's birthday (dd/mm/yyyy): "))
print("Peter's birthday is on", peter)
print("Parker's birthday is on", parker)
print("Tom's birthday is on", tom)
print("Mitchell's birthday is on", mitchell)
print("Tim's birthday is on", tim)